// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEWphvDgPq9t_nO2JWaYwxAH71YdTaIXE',
    appId: '1:1031412747377:web:442e957a95d723821adfd0',
    messagingSenderId: '1031412747377',
    projectId: 'iotanimal-2c984',
    authDomain: 'iotanimal-2c984.firebaseapp.com',
    storageBucket: 'iotanimal-2c984.firebasestorage.app',
    measurementId: 'G-FB7DF9XLT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnZENBhX_igaSi9mFlHq72xcm95UTGRM',
    appId: '1:1031412747377:android:68afe0d83ca28c561adfd0',
    messagingSenderId: '1031412747377',
    projectId: 'iotanimal-2c984',
    storageBucket: 'iotanimal-2c984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fWOy8rOIFvWq2CWTrPDNOotXBIKs5JM',
    appId: '1:1031412747377:ios:cc9e5f3c5ed357dc1adfd0',
    messagingSenderId: '1031412747377',
    projectId: 'iotanimal-2c984',
    storageBucket: 'iotanimal-2c984.firebasestorage.app',
    iosBundleId: 'com.example.animalDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6fWOy8rOIFvWq2CWTrPDNOotXBIKs5JM',
    appId: '1:1031412747377:ios:cc9e5f3c5ed357dc1adfd0',
    messagingSenderId: '1031412747377',
    projectId: 'iotanimal-2c984',
    storageBucket: 'iotanimal-2c984.firebasestorage.app',
    iosBundleId: 'com.example.animalDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEWphvDgPq9t_nO2JWaYwxAH71YdTaIXE',
    appId: '1:1031412747377:web:27b981e0e87416521adfd0',
    messagingSenderId: '1031412747377',
    projectId: 'iotanimal-2c984',
    authDomain: 'iotanimal-2c984.firebaseapp.com',
    storageBucket: 'iotanimal-2c984.firebasestorage.app',
    measurementId: 'G-81JCN9991K',
  );
}
